apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patches:
  - deployment.yaml
  - service.yaml

replicas:
  - name: vote
    count: 2

images:
  - name: schoolofdevops/vote
    newTag: v4

namespace: instavote

labels:
  project: env
  env: staging

commonAnnotations:
  supported-by: "Me"

configMapGenerator:
  - name: vote-options
    envs:
      - options.env

