apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
    tier: front
  name: vote
  namespace: instavote
spec:
  ports:
  - name: "80"
    nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
